[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fyrefly"
version = "0.3.1"
description = "A quant-based library to compute mathematical operations, run SQL queries, get AI-powered insights, and visualize your data."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Ninad Mandavkar", email = "ninadmandavkar28@gmail.com" }
]
keywords = ["math", "arithmetic", "quant", "utility", "sql", "pandas", "ai", "visualization"]
dependencies = [
    "pandas",
    "duckdb",
    "openpyxl",
    "requests",
    "matplotlib",
    "seaborn",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/Ninad077/fyrefly"
Repository = "https://github.com/Ninad077/fyrefly"

[project.optional-dependencies]
dev = ["pytest>=7.0"]